window.NC2000_JA_NAMES = {
  "pokemon": {
    "Bulbasaur": "フシギダネ",
    "Ivysaur": "フシギソウ",
    "Venusaur": "フシギバナ",
    "Venusaur-Gmax": "フシギバナ",
    "Venusaur-Mega": "フシギバナ",
    "Charmander": "ヒトカゲ",
    "Charmeleon": "リザード",
    "Charizard": "リザードン",
    "Charizard-Gmax": "リザードン",
    "Charizard-Mega-X": "リザードン",
    "Charizard-Mega-Y": "リザードン",
    "Squirtle": "ゼニガメ",
    "Wartortle": "カメール",
    "Blastoise": "カメックス",
    "Blastoise-Gmax": "カメックス",
    "Blastoise-Mega": "カメックス",
    "Caterpie": "キャタピー",
    "Metapod": "トランセル",
    "Butterfree": "バタフリー",
    "Butterfree-Gmax": "バタフリー",
    "Weedle": "ビードル",
    "Kakuna": "コクーン",
    "Beedrill": "スピアー",
    "Beedrill-Mega": "スピアー",
    "Pidgey": "ポッポ",
    "Pidgeotto": "ピジョン",
    "Pidgeot": "ピジョット",
    "Pidgeot-Mega": "ピジョット",
    "Rattata": "コラッタ",
    "Rattata-Alola": "コラッタ",
    "Raticate": "ラッタ",
    "Raticate-Alola": "ラッタ",
    "Raticate-Alola-Totem": "ラッタ",
    "Spearow": "オニスズメ",
    "Fearow": "オニドリル",
    "Ekans": "アーボ",
    "Arbok": "アーボック",
    "Pikachu": "ピカチュウ",
    "Pikachu-Alola": "ピカチュウ",
    "Pikachu-Belle": "ピカチュウ",
    "Pikachu-Cosplay": "ピカチュウ",
    "Pikachu-Gmax": "ピカチュウ",
    "Pikachu-Hoenn": "ピカチュウ",
    "Pikachu-Kalos": "ピカチュウ",
    "Pikachu-Libre": "ピカチュウ",
    "Pikachu-Original": "ピカチュウ",
    "Pikachu-Partner": "ピカチュウ",
    "Pikachu-PhD": "ピカチュウ",
    "Pikachu-Pop-Star": "ピカチュウ",
    "Pikachu-Rock-Star": "ピカチュウ",
    "Pikachu-Sinnoh": "ピカチュウ",
    "Pikachu-Starter": "ピカチュウ",
    "Pikachu-Unova": "ピカチュウ",
    "Pikachu-World": "ピカチュウ",
    "Raichu": "ライチュウ",
    "Raichu-Alola": "ライチュウ",
    "Raichu-Mega-X": "ライチュウ",
    "Raichu-Mega-Y": "ライチュウ",
    "Sandshrew": "サンド",
    "Sandshrew-Alola": "サンド",
    "Sandslash": "サンドパン",
    "Sandslash-Alola": "サンドパン",
    "Nidoran-F": "ニドラン♀",
    "Nidorina": "ニドリーナ",
    "Nidoqueen": "ニドクイン",
    "Nidoran-M": "ニドラン♂",
    "Nidorino": "ニドリーノ",
    "Nidoking": "ニドキング",
    "Clefairy": "ピッピ",
    "Clefable": "ピクシー",
    "Clefable-Mega": "ピクシー",
    "Vulpix": "ロコン",
    "Vulpix-Alola": "ロコン",
    "Ninetales": "キュウコン",
    "Ninetales-Alola": "キュウコン",
    "Jigglypuff": "プリン",
    "Wigglytuff": "プクリン",
    "Zubat": "ズバット",
    "Golbat": "ゴルバット",
    "Oddish": "ナゾノクサ",
    "Gloom": "クサイハナ",
    "Vileplume": "ラフレシア",
    "Paras": "パラス",
    "Parasect": "パラセクト",
    "Venonat": "コンパン",
    "Venomoth": "モルフォン",
    "Diglett": "ディグダ",
    "Diglett-Alola": "ディグダ",
    "Dugtrio": "ダグトリオ",
    "Dugtrio-Alola": "ダグトリオ",
    "Meowth": "ニャース",
    "Meowth-Alola": "ニャース",
    "Meowth-Galar": "ニャース",
    "Meowth-Gmax": "ニャース",
    "Persian": "ペルシアン",
    "Persian-Alola": "ペルシアン",
    "Psyduck": "コダック",
    "Golduck": "ゴルダック",
    "Mankey": "マンキー",
    "Primeape": "オコリザル",
    "Growlithe": "ガーディ",
    "Growlithe-Hisui": "ガーディ",
    "Arcanine": "ウインディ",
    "Arcanine-Hisui": "ウインディ",
    "Poliwag": "ニョロモ",
    "Poliwhirl": "ニョロゾ",
    "Poliwrath": "ニョロボン",
    "Abra": "ケーシィ",
    "Kadabra": "ユンゲラー",
    "Alakazam": "フーディン",
    "Alakazam-Mega": "フーディン",
    "Machop": "ワンリキー",
    "Machoke": "ゴーリキー",
    "Machamp": "カイリキー",
    "Machamp-Gmax": "カイリキー",
    "Bellsprout": "マダツボミ",
    "Weepinbell": "ウツドン",
    "Victreebel": "ウツボット",
    "Victreebel-Mega": "ウツボット",
    "Tentacool": "メノクラゲ",
    "Tentacruel": "ドククラゲ",
    "Geodude": "イシツブテ",
    "Geodude-Alola": "イシツブテ",
    "Graveler": "ゴローン",
    "Graveler-Alola": "ゴローン",
    "Golem": "ゴローニャ",
    "Golem-Alola": "ゴローニャ",
    "Ponyta": "ポニータ",
    "Ponyta-Galar": "ポニータ",
    "Rapidash": "ギャロップ",
    "Rapidash-Galar": "ギャロップ",
    "Slowpoke": "ヤドン",
    "Slowpoke-Galar": "ヤドン",
    "Slowbro": "ヤドラン",
    "Slowbro-Galar": "ヤドラン",
    "Slowbro-Mega": "ヤドラン",
    "Magnemite": "コイル",
    "Magneton": "レアコイル",
    "Farfetch’d": "カモネギ",
    "Farfetch’d-Galar": "カモネギ",
    "Doduo": "ドードー",
    "Dodrio": "ドードリオ",
    "Seel": "パウワウ",
    "Dewgong": "ジュゴン",
    "Grimer": "ベトベター",
    "Grimer-Alola": "ベトベター",
    "Muk": "ベトベトン",
    "Muk-Alola": "ベトベトン",
    "Shellder": "シェルダー",
    "Cloyster": "パルシェン",
    "Gastly": "ゴース",
    "Haunter": "ゴースト",
    "Gengar": "ゲンガー",
    "Gengar-Gmax": "ゲンガー",
    "Gengar-Mega": "ゲンガー",
    "Onix": "イワーク",
    "Drowzee": "スリープ",
    "Hypno": "スリーパー",
    "Krabby": "クラブ",
    "Kingler": "キングラー",
    "Kingler-Gmax": "キングラー",
    "Voltorb": "ビリリダマ",
    "Voltorb-Hisui": "ビリリダマ",
    "Electrode": "マルマイン",
    "Electrode-Hisui": "マルマイン",
    "Exeggcute": "タマタマ",
    "Exeggutor": "ナッシー",
    "Exeggutor-Alola": "ナッシー",
    "Cubone": "カラカラ",
    "Marowak": "ガラガラ",
    "Marowak-Alola": "ガラガラ",
    "Marowak-Alola-Totem": "ガラガラ",
    "Hitmonlee": "サワムラー",
    "Hitmonchan": "エビワラー",
    "Lickitung": "ベロリンガ",
    "Koffing": "ドガース",
    "Weezing": "マタドガス",
    "Weezing-Galar": "マタドガス",
    "Rhyhorn": "サイホーン",
    "Rhydon": "サイドン",
    "Chansey": "ラッキー",
    "Tangela": "モンジャラ",
    "Kangaskhan": "ガルーラ",
    "Kangaskhan-Mega": "ガルーラ",
    "Horsea": "タッツー",
    "Seadra": "シードラ",
    "Goldeen": "トサキント",
    "Seaking": "アズマオウ",
    "Staryu": "ヒトデマン",
    "Starmie": "スターミー",
    "Starmie-Mega": "スターミー",
    "Mr. Mime": "バリヤード",
    "Mr. Mime-Galar": "バリヤード",
    "Scyther": "ストライク",
    "Jynx": "ルージュラ",
    "Electabuzz": "エレブー",
    "Magmar": "ブーバー",
    "Pinsir": "カイロス",
    "Pinsir-Mega": "カイロス",
    "Tauros": "ケンタロス",
    "Tauros-Paldea-Aqua": "ケンタロス",
    "Tauros-Paldea-Blaze": "ケンタロス",
    "Tauros-Paldea-Combat": "ケンタロス",
    "Magikarp": "コイキング",
    "Gyarados": "ギャラドス",
    "Gyarados-Mega": "ギャラドス",
    "Lapras": "ラプラス",
    "Lapras-Gmax": "ラプラス",
    "Ditto": "メタモン",
    "Eevee": "イーブイ",
    "Eevee-Gmax": "イーブイ",
    "Eevee-Starter": "イーブイ",
    "Vaporeon": "シャワーズ",
    "Jolteon": "サンダース",
    "Flareon": "ブースター",
    "Porygon": "ポリゴン",
    "Omanyte": "オムナイト",
    "Omastar": "オムスター",
    "Kabuto": "カブト",
    "Kabutops": "カブトプス",
    "Aerodactyl": "プテラ",
    "Aerodactyl-Mega": "プテラ",
    "Snorlax": "カビゴン",
    "Snorlax-Gmax": "カビゴン",
    "Articuno": "フリーザー",
    "Articuno-Galar": "フリーザー",
    "Zapdos": "サンダー",
    "Zapdos-Galar": "サンダー",
    "Moltres": "ファイヤー",
    "Moltres-Galar": "ファイヤー",
    "Dratini": "ミニリュウ",
    "Dragonair": "ハクリュー",
    "Dragonite": "カイリュー",
    "Dragonite-Mega": "カイリュー",
    "Mewtwo": "ミュウツー",
    "Mewtwo-Mega-X": "ミュウツー",
    "Mewtwo-Mega-Y": "ミュウツー",
    "Mew": "ミュウ",
    "Chikorita": "チコリータ",
    "Bayleef": "ベイリーフ",
    "Meganium": "メガニウム",
    "Meganium-Mega": "メガニウム",
    "Cyndaquil": "ヒノアラシ",
    "Quilava": "マグマラシ",
    "Typhlosion": "バクフーン",
    "Typhlosion-Hisui": "バクフーン",
    "Totodile": "ワニノコ",
    "Croconaw": "アリゲイツ",
    "Feraligatr": "オーダイル",
    "Feraligatr-Mega": "オーダイル",
    "Sentret": "オタチ",
    "Furret": "オオタチ",
    "Hoothoot": "ホーホー",
    "Noctowl": "ヨルノズク",
    "Ledyba": "レディバ",
    "Ledian": "レディアン",
    "Spinarak": "イトマル",
    "Ariados": "アリアドス",
    "Crobat": "クロバット",
    "Chinchou": "チョンチー",
    "Lanturn": "ランターン",
    "Pichu": "ピチュー",
    "Pichu-Spiky-eared": "ピチュー",
    "Cleffa": "ピィ",
    "Igglybuff": "ププリン",
    "Togepi": "トゲピー",
    "Togetic": "トゲチック",
    "Natu": "ネイティ",
    "Xatu": "ネイティオ",
    "Mareep": "メリープ",
    "Flaaffy": "モココ",
    "Ampharos": "デンリュウ",
    "Ampharos-Mega": "デンリュウ",
    "Bellossom": "キレイハナ",
    "Marill": "マリル",
    "Azumarill": "マリルリ",
    "Sudowoodo": "ウソッキー",
    "Politoed": "ニョロトノ",
    "Hoppip": "ハネッコ",
    "Skiploom": "ポポッコ",
    "Jumpluff": "ワタッコ",
    "Aipom": "エイパム",
    "Sunkern": "ヒマナッツ",
    "Sunflora": "キマワリ",
    "Yanma": "ヤンヤンマ",
    "Wooper": "ウパー",
    "Wooper-Paldea": "ウパー",
    "Quagsire": "ヌオー",
    "Espeon": "エーフィ",
    "Umbreon": "ブラッキー",
    "Murkrow": "ヤミカラス",
    "Slowking": "ヤドキング",
    "Slowking-Galar": "ヤドキング",
    "Misdreavus": "ムウマ",
    "Unown": "アンノーン",
    "Wobbuffet": "ソーナンス",
    "Girafarig": "キリンリキ",
    "Pineco": "クヌギダマ",
    "Forretress": "フォレトス",
    "Dunsparce": "ノコッチ",
    "Gligar": "グライガー",
    "Steelix": "ハガネール",
    "Steelix-Mega": "ハガネール",
    "Snubbull": "ブルー",
    "Granbull": "グランブル",
    "Qwilfish": "ハリーセン",
    "Qwilfish-Hisui": "ハリーセン",
    "Scizor": "ハッサム",
    "Scizor-Mega": "ハッサム",
    "Shuckle": "ツボツボ",
    "Heracross": "ヘラクロス",
    "Heracross-Mega": "ヘラクロス",
    "Sneasel": "ニューラ",
    "Sneasel-Hisui": "ニューラ",
    "Teddiursa": "ヒメグマ",
    "Ursaring": "リングマ",
    "Slugma": "マグマッグ",
    "Magcargo": "マグカルゴ",
    "Swinub": "ウリムー",
    "Piloswine": "イノムー",
    "Corsola": "サニーゴ",
    "Corsola-Galar": "サニーゴ",
    "Remoraid": "テッポウオ",
    "Octillery": "オクタン",
    "Delibird": "デリバード",
    "Mantine": "マンタイン",
    "Skarmory": "エアームド",
    "Skarmory-Mega": "エアームド",
    "Houndour": "デルビル",
    "Houndoom": "ヘルガー",
    "Houndoom-Mega": "ヘルガー",
    "Kingdra": "キングドラ",
    "Phanpy": "ゴマゾウ",
    "Donphan": "ドンファン",
    "Porygon2": "ポリゴン２",
    "Stantler": "オドシシ",
    "Smeargle": "ドーブル",
    "Tyrogue": "バルキー",
    "Hitmontop": "カポエラー",
    "Smoochum": "ムチュール",
    "Elekid": "エレキッド",
    "Magby": "ブビィ",
    "Miltank": "ミルタンク",
    "Blissey": "ハピナス",
    "Raikou": "ライコウ",
    "Entei": "エンテイ",
    "Suicune": "スイクン",
    "Larvitar": "ヨーギラス",
    "Pupitar": "サナギラス",
    "Tyranitar": "バンギラス",
    "Tyranitar-Mega": "バンギラス",
    "Lugia": "ルギア",
    "Ho-Oh": "ホウオウ",
    "Celebi": "セレビィ"
  },
  "moves": {
    "Pound": "はたく",
    "Karate Chop": "からてチョップ",
    "Double Slap": "おうふくビンタ",
    "Comet Punch": "れんぞくパンチ",
    "Mega Punch": "メガトンパンチ",
    "Pay Day": "ネコにこばん",
    "Fire Punch": "ほのおのパンチ",
    "Ice Punch": "れいとうパンチ",
    "Thunder Punch": "かみなりパンチ",
    "Scratch": "ひっかく",
    "Vise Grip": "はさむ",
    "Guillotine": "ハサミギロチン",
    "Razor Wind": "かまいたち",
    "Swords Dance": "つるぎのまい",
    "Cut": "いあいぎり",
    "Gust": "かぜおこし",
    "Wing Attack": "つばさでうつ",
    "Whirlwind": "ふきとばし",
    "Fly": "そらをとぶ",
    "Bind": "しめつける",
    "Slam": "たたきつける",
    "Vine Whip": "つるのムチ",
    "Stomp": "ふみつけ",
    "Double Kick": "にどげり",
    "Mega Kick": "メガトンキック",
    "Jump Kick": "とびげり",
    "Rolling Kick": "まわしげり",
    "Sand Attack": "すなかけ",
    "Headbutt": "ずつき",
    "Horn Attack": "つのでつく",
    "Fury Attack": "みだれづき",
    "Horn Drill": "つのドリル",
    "Tackle": "たいあたり",
    "Body Slam": "のしかかり",
    "Wrap": "まきつく",
    "Take Down": "とっしん",
    "Thrash": "あばれる",
    "Double-Edge": "すてみタックル",
    "Tail Whip": "しっぽをふる",
    "Poison Sting": "どくばり",
    "Twineedle": "ダブルニードル",
    "Pin Missile": "ミサイルばり",
    "Leer": "にらみつける",
    "Bite": "かみつく",
    "Growl": "なきごえ",
    "Roar": "ほえる",
    "Sing": "うたう",
    "Supersonic": "ちょうおんぱ",
    "Sonic Boom": "ソニックブーム",
    "Disable": "かなしばり",
    "Acid": "ようかいえき",
    "Ember": "ひのこ",
    "Flamethrower": "かえんほうしゃ",
    "Mist": "しろいきり",
    "Water Gun": "みずでっぽう",
    "Hydro Pump": "ハイドロポンプ",
    "Surf": "なみのり",
    "Ice Beam": "れいとうビーム",
    "Blizzard": "ふぶき",
    "Psybeam": "サイケこうせん",
    "Bubble Beam": "バブルこうせん",
    "Aurora Beam": "オーロラビーム",
    "Hyper Beam": "はかいこうせん",
    "Peck": "つつく",
    "Drill Peck": "ドリルくちばし",
    "Submission": "じごくぐるま",
    "Low Kick": "けたぐり",
    "Counter": "カウンター",
    "Seismic Toss": "ちきゅうなげ",
    "Strength": "かいりき",
    "Absorb": "すいとる",
    "Mega Drain": "メガドレイン",
    "Leech Seed": "やどりぎのタネ",
    "Growth": "せいちょう",
    "Razor Leaf": "はっぱカッター",
    "Solar Beam": "ソーラービーム",
    "Poison Powder": "どくのこな",
    "Stun Spore": "しびれごな",
    "Sleep Powder": "ねむりごな",
    "Petal Dance": "はなびらのまい",
    "String Shot": "いとをはく",
    "Dragon Rage": "りゅうのいかり",
    "Fire Spin": "ほのおのうず",
    "Thunder Shock": "でんきショック",
    "Thunderbolt": "１０まんボルト",
    "Thunder Wave": "でんじは",
    "Thunder": "かみなり",
    "Rock Throw": "いわおとし",
    "Earthquake": "じしん",
    "Fissure": "じわれ",
    "Dig": "あなをほる",
    "Toxic": "どくどく",
    "Confusion": "ねんりき",
    "Psychic": "サイコキネシス",
    "Hypnosis": "さいみんじゅつ",
    "Meditate": "ヨガのポーズ",
    "Agility": "こうそくいどう",
    "Quick Attack": "でんこうせっか",
    "Rage": "いかり",
    "Teleport": "テレポート",
    "Night Shade": "ナイトヘッド",
    "Mimic": "ものまね",
    "Screech": "いやなおと",
    "Double Team": "かげぶんしん",
    "Recover": "じこさいせい",
    "Harden": "かたくなる",
    "Minimize": "ちいさくなる",
    "Smokescreen": "えんまく",
    "Confuse Ray": "あやしいひかり",
    "Withdraw": "からにこもる",
    "Defense Curl": "まるくなる",
    "Barrier": "バリアー",
    "Light Screen": "ひかりのかべ",
    "Haze": "くろいきり",
    "Reflect": "リフレクター",
    "Focus Energy": "きあいだめ",
    "Bide": "がまん",
    "Metronome": "ゆびをふる",
    "Mirror Move": "オウムがえし",
    "Self-Destruct": "じばく",
    "Egg Bomb": "タマゴばくだん",
    "Lick": "したでなめる",
    "Smog": "スモッグ",
    "Sludge": "ヘドロこうげき",
    "Bone Club": "ホネこんぼう",
    "Fire Blast": "だいもんじ",
    "Waterfall": "たきのぼり",
    "Clamp": "からではさむ",
    "Swift": "スピードスター",
    "Skull Bash": "ロケットずつき",
    "Spike Cannon": "とげキャノン",
    "Constrict": "からみつく",
    "Amnesia": "ドわすれ",
    "Kinesis": "スプーンまげ",
    "Soft-Boiled": "タマゴうみ",
    "High Jump Kick": "とびひざげり",
    "Glare": "へびにらみ",
    "Dream Eater": "ゆめくい",
    "Poison Gas": "どくガス",
    "Barrage": "たまなげ",
    "Leech Life": "きゅうけつ",
    "Lovely Kiss": "あくまのキッス",
    "Sky Attack": "ゴッドバード",
    "Transform": "へんしん",
    "Bubble": "あわ",
    "Dizzy Punch": "ピヨピヨパンチ",
    "Spore": "キノコのほうし",
    "Flash": "フラッシュ",
    "Psywave": "サイコウェーブ",
    "Splash": "はねる",
    "Acid Armor": "とける",
    "Crabhammer": "クラブハンマー",
    "Explosion": "だいばくはつ",
    "Fury Swipes": "みだれひっかき",
    "Bonemerang": "ホネブーメラン",
    "Rest": "ねむる",
    "Rock Slide": "いわなだれ",
    "Hyper Fang": "ひっさつまえば",
    "Sharpen": "かくばる",
    "Conversion": "テクスチャー",
    "Tri Attack": "トライアタック",
    "Super Fang": "いかりのまえば",
    "Slash": "きりさく",
    "Substitute": "みがわり",
    "Struggle": "わるあがき",
    "Sketch": "スケッチ",
    "Triple Kick": "トリプルキック",
    "Thief": "どろぼう",
    "Spider Web": "クモのす",
    "Mind Reader": "こころのめ",
    "Nightmare": "あくむ",
    "Flame Wheel": "かえんぐるま",
    "Snore": "いびき",
    "Curse": "のろい",
    "Flail": "じたばた",
    "Conversion 2": "テクスチャー２",
    "Aeroblast": "エアロブラスト",
    "Cotton Spore": "わたほうし",
    "Reversal": "きしかいせい",
    "Spite": "うらみ",
    "Powder Snow": "こなゆき",
    "Protect": "まもる",
    "Mach Punch": "マッハパンチ",
    "Scary Face": "こわいかお",
    "Feint Attack": "だましうち",
    "Sweet Kiss": "てんしのキッス",
    "Belly Drum": "はらだいこ",
    "Sludge Bomb": "ヘドロばくだん",
    "Mud-Slap": "どろかけ",
    "Octazooka": "オクタンほう",
    "Spikes": "まきびし",
    "Zap Cannon": "でんじほう",
    "Foresight": "みやぶる",
    "Destiny Bond": "みちづれ",
    "Perish Song": "ほろびのうた",
    "Icy Wind": "こごえるかぜ",
    "Detect": "みきり",
    "Bone Rush": "ボーンラッシュ",
    "Lock-On": "ロックオン",
    "Outrage": "げきりん",
    "Sandstorm": "すなあらし",
    "Giga Drain": "ギガドレイン",
    "Endure": "こらえる",
    "Charm": "あまえる",
    "Rollout": "ころがる",
    "False Swipe": "みねうち",
    "Swagger": "いばる",
    "Milk Drink": "ミルクのみ",
    "Spark": "スパーク",
    "Fury Cutter": "れんぞくぎり",
    "Steel Wing": "はがねのつばさ",
    "Mean Look": "くろいまなざし",
    "Attract": "メロメロ",
    "Sleep Talk": "ねごと",
    "Heal Bell": "いやしのすず",
    "Return": "おんがえし",
    "Present": "プレゼント",
    "Frustration": "やつあたり",
    "Safeguard": "しんぴのまもり",
    "Pain Split": "いたみわけ",
    "Sacred Fire": "せいなるほのお",
    "Magnitude": "マグニチュード",
    "Dynamic Punch": "ばくれつパンチ",
    "Megahorn": "メガホーン",
    "Dragon Breath": "りゅうのいぶき",
    "Baton Pass": "バトンタッチ",
    "Encore": "アンコール",
    "Pursuit": "おいうち",
    "Rapid Spin": "こうそくスピン",
    "Sweet Scent": "あまいかおり",
    "Iron Tail": "アイアンテール",
    "Metal Claw": "メタルクロー",
    "Vital Throw": "あてみなげ",
    "Morning Sun": "あさのひざし",
    "Synthesis": "こうごうせい",
    "Moonlight": "つきのひかり",
    "Hidden Power": "めざめるパワー",
    "Hidden Power Bug": "めざめるパワー 虫",
    "Hidden Power Dark": "めざめるパワー 悪",
    "Hidden Power Dragon": "めざめるパワー ドラゴン",
    "Hidden Power Electric": "めざめるパワー 電気",
    "Hidden Power Fighting": "めざめるパワー 格闘",
    "Hidden Power Fire": "めざめるパワー 炎",
    "Hidden Power Flying": "めざめるパワー 飛行",
    "Hidden Power Ghost": "めざめるパワー ゴースト",
    "Hidden Power Grass": "めざめるパワー 草",
    "Hidden Power Ground": "めざめるパワー 地面",
    "Hidden Power Ice": "めざめるパワー 氷",
    "Hidden Power Poison": "めざめるパワー 毒",
    "Hidden Power Psychic": "めざめるパワー エスパー",
    "Hidden Power Rock": "めざめるパワー 岩",
    "Hidden Power Steel": "めざめるパワー 鋼",
    "Hidden Power Water": "めざめるパワー 水",
    "Cross Chop": "クロスチョップ",
    "Twister": "たつまき",
    "Rain Dance": "あまごい",
    "Sunny Day": "にほんばれ",
    "Crunch": "かみくだく",
    "Mirror Coat": "ミラーコート",
    "Psych Up": "じこあんじ",
    "Extreme Speed": "しんそく",
    "Ancient Power": "げんしのちから",
    "Shadow Ball": "シャドーボール",
    "Future Sight": "みらいよち",
    "Rock Smash": "いわくだき",
    "Whirlpool": "うずしお",
    "Beat Up": "ふくろだたき",
    "Hidden Power [Bug]": "めざめるパワー 虫",
    "Hidden Power [Dark]": "めざめるパワー 悪",
    "Hidden Power [Dragon]": "めざめるパワー ドラゴン",
    "Hidden Power [Electric]": "めざめるパワー 電気",
    "Hidden Power [Fighting]": "めざめるパワー 格闘",
    "Hidden Power [Fire]": "めざめるパワー 炎",
    "Hidden Power [Flying]": "めざめるパワー 飛行",
    "Hidden Power [Ghost]": "めざめるパワー ゴースト",
    "Hidden Power [Grass]": "めざめるパワー 草",
    "Hidden Power [Ground]": "めざめるパワー 地面",
    "Hidden Power [Ice]": "めざめるパワー 氷",
    "Hidden Power [Poison]": "めざめるパワー 毒",
    "Hidden Power [Psychic]": "めざめるパワー エスパー",
    "Hidden Power [Rock]": "めざめるパワー 岩",
    "Hidden Power [Steel]": "めざめるパワー 鋼",
    "Hidden Power [Water]": "めざめるパワー 水"
  },
  "items": {
    "Berry": "きのみ",
    "Berry Juice": "きのみジュース",
    "Berserk Gene": "はかいのいでんし",
    "Bitter Berry": "にがいきのみ",
    "Black Belt": "くろおび",
    "Black Glasses": "くろいメガネ",
    "Bright Powder": "ひかりのこな",
    "Burnt Berry": "やけたきのみ",
    "Charcoal": "もくたん",
    "Dragon Fang": "りゅうのキバ",
    "Dragon Scale": "りゅうのウロコ",
    "Fast Ball": "スピードボール",
    "Fire Stone": "ほのおのいし",
    "Focus Band": "きあいのハチマキ",
    "Friend Ball": "フレンドボール",
    "Gold Berry": "おうごんのみ",
    "Great Ball": "スーパーボール",
    "Hard Stone": "かたいいし",
    "Heavy Ball": "ヘビーボール",
    "Ice Berry": "こおったきのみ",
    "King's Rock": "おうじゃのしるし",
    "Leaf Stone": "リーフのいし",
    "Leftovers": "たべのこし",
    "Level Ball": "レベルボール",
    "Light Ball": "でんきだま",
    "Love Ball": "ラブラブボール",
    "Lucky Punch": "ラッキーパンチ",
    "Lure Ball": "ルアーボール",
    "Magnet": "じしゃく",
    "Mail": "メール",
    "Master Ball": "マスターボール",
    "Metal Coat": "メタルコート",
    "Metal Powder": "メタルパウダー",
    "Mint Berry": "はっかのみ",
    "Miracle Berry": "きせきのみ",
    "Miracle Seed": "きせきのタネ",
    "Moon Ball": "ムーンボール",
    "Moon Stone": "つきのいし",
    "Mystery Berry": "ふしぎなきのみ",
    "Mystic Water": "しんぴのしずく",
    "Never-Melt Ice": "とけないこおり",
    "Pink Bow": "ぴんくのリボン",
    "Poison Barb": "どくバリ",
    "Poke Ball": "モンスターボール",
    "Polkadot Bow": "みずたまリボン",
    "PRZ Cure Berry": "まひなおしのみ",
    "PSN Cure Berry": "どくけしのみ",
    "Quick Claw": "せんせいのツメ",
    "Safari Ball": "サファリボール",
    "Scope Lens": "ピントレンズ",
    "Sharp Beak": "するどいくちばし",
    "Silver Powder": "ぎんのこな",
    "Soft Sand": "やわらかいすな",
    "Spell Tag": "のろいのおふだ",
    "Sport Ball": "コンペボール",
    "Stick": "ながねぎ",
    "Sun Stone": "たいようのいし",
    "Thick Club": "ふといホネ",
    "Thunder Stone": "かみなりのいし",
    "Twisted Spoon": "まがったスプーン",
    "Ultra Ball": "ハイパーボール",
    "Up-Grade": "アップグレード",
    "Water Stone": "みずのいし"
  }
};
